### ISSUE TITLE
(DynamicPriceSale.sol) Test Deployment of crowdsale

### ISSUE THREAD

**Issue by juliencharrel** [closerdao/proof-of-presence#36]
- Deploy 1 fake 10^18 decimals ERC20 called testEUR (you can use src/ERC20/TDFToken in the repo since it already has a mint function ==> please don't forget to transfer ownership at the end so I can mint)
- Deploy the Crowdsale contract on alfajores with:
-- token: the TDF contract here: 0xA1885AC1A36C645651CE267ac15E8d33FC34446e
-- quote: the above fake cEur
-- minter: the diamond DAO contract here: 0x743C187B61EfDdD464722afdC40738FDa7ADD6B3

- Transfer ownership of the crowdsale and test EUR contract to 0xbE5B7A0F27e7Ec296670c3fc7c34BE652303e716

**Comment by arturictus** [comment]
@juliencharrel what's the status of this?
What is the test about?, manual test?, fronted test?, scripts?

**Comment by arturictus** [comment]
I close it because of inactivity
