### ISSUE TITLE
TestTimestamp fails when user is in GMT+13 (and bookings might be broken)

### ISSUE THREAD

**Issue by juliencharrel** [closerdao/proof-of-presence#46]
Maybe in other timezones too.

**Comment by arturictus** [comment]
> and bookings might be broken

can you elaborate how this would affect bookings in the contracts?

The current issue is in test, the TS that is testing the timestamp is doing calculations with a difference timezone that the test hardhat EVM. That's the main cause of this error.

Timestamps are calculated in the contract, the client should send `year` and `day of the year` (1-365).
Client should make sure that those two params are calculated from a UTC time before sending them to the blockchain.

**Comment by juliencharrel** [comment]
And good to know it does not impact booking

**Comment by arturictus** [comment]
CI is working, would be nice that the next developer that finds this issue fixes it.
I close it for now
