### ISSUE TITLE
Get the REAL token addresses for dynamic sale

### ISSUE THREAD

**Issue by arturictus** [closerdao/proof-of-presence#48]
We need someone to find and verify the addresses for ceur in alfajores and mainnet and write them down here.
- [x] get alfajores `ceur` address`
- [x] get mainnet `ceur` address
- [ ] topup developers addresses with test ceur
   - [x] Artur `0x661Ac71bbe43fe56935c1CA4d62e62ed380950A3`
   - [x] Julien `0x346314781c4D1483bE27fAEA9d698074f7cBa1Be`
   - [ ] Sam

**Comment by juliencharrel** [comment]
Just to confirm @arturictus We're not using these addresses for mainnet launch.
Also not sure what you want to test on Alfajores with cEur but the faucet is limited to 5 cEUR each time
