### ISSUE TITLE
March 16: Transfer ownership of smartcontract

### ISSUE THREAD

**Issue by marektucek** [closerdao/proof-of-presence#59]
transfer to traditionaldreamfactory.eth

**Comment by Zitzak** [comment]
Could you detail what is meant by this issue. Which contracts are meant? Also the ENS resolves to an Ethereum address. Assuming that it was created in a way that the Celo address is also owned?

Lastly, I assumed that contracts should be owned by the multi-sig. Is this not the case?

Thanks for your help :)
@marektucek
